name: odp
channels:
  - plotly
  - conda-forge
  - cornell-zhang
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alsa-lib=1.2.8=h166bdaf_0
  - attr=2.5.1=h166bdaf_1
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py38h0a891b7_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2023.01.10=h06a4308_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.15.1=py38h4a40e3a_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=22.11.1=py38h578d9bd_1
  - conda-package-handling=2.0.2=pyh38be061_0
  - conda-package-streaming=0.7.0=pyhd8ed1ab_1
  - contourpy=1.0.7=py38hfbd4bf9_0
  - cryptography=39.0.0=py38h3d167d9_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - decorator=5.1.1=pyhd3eb1b0_0
  - expat=2.5.0=h27087fc_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - fmt=9.1.0=h924138e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py38h0a891b7_1
  - freetype=2.12.1=hca18f0e_1
  - future=0.18.2=py38_1
  - gettext=0.21.1=h27087fc_0
  - glib=2.74.1=h6239696_1
  - glib-tools=2.74.1=h6239696_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.33=h166bdaf_0
  - harfbuzz=6.0.0=h8e241bc_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - jack=1.9.22=h11f4161_0
  - jpeg=9e=h166bdaf_2
  - kaleido-core=0.2.1=h3644ca4_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py38h43d8883_1
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=hfd0df8a_1
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libarchive=3.6.2=h3d51595_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=15.0.7=default_had23c3d_0
  - libclang13=15.0.7=default_h3e3d535_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.87.0=hdc1c0ab_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.2=h6a678d5_6
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libgpg-error=1.46=h620e276_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm15=15.0.7=hadd5161_0
  - libmamba=1.2.0=hcea66bb_0
  - libmambapy=1.2.0=py38h7fa060d_0
  - libnghttp2=1.51.0=hff17c54_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.1=hb675445_3
  - libsndfile=1.2.0=hb75c966_0
  - libsolv=0.7.23=h3eb15da_0
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=252=h2a991cd_0
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.4.7=h27087fc_0
  - libudev1=252=h166bdaf_0
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.7=h0cdce71_0
  - llvmdev=6.0.0=h1a6f6a4_4
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mamba=1.2.0=py38haad2881_0
  - matplotlib=3.6.3=py38h578d9bd_0
  - matplotlib-base=3.6.3=py38hd6c3c57_0
  - mathjax=2.7.7=ha770c72_3 
  - mpg123=1.31.2=hcb278e6_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.32=ha901b37_0
  - mysql-libs=8.0.32=hd7da12d_0
  - ncurses=6.4=h6a678d5_0
  - networkx=2.8.8=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.82=he02c5a1_0
  - numpy=1.24.1=py38h10c12cc_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.0.7=h0b41bf4_2
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - packaging=23.0=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pillow=9.4.0=py38hb32c036_0
  - pip=22.3.1=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - plotly=5.13.0=py_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio=16.1=ha8d29e2_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.4=py38h0a891b7_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py38ha0d8c90_3
  - pyqt5-sip=12.11.0=py38h8dc9893_3
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.16=he550d4f_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - python-kaleido-0.2.1-pyhd8ed1ab_0
  - qt-main=5.15.6=h602db52_6
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h0b41bf4_0
  - reproc-cpp=14.2.4=hcb278e6_0
  - requests=2.28.2=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py38h0a891b7_2
  - ruamel.yaml.clib=0.2.7=py38h1de0b5d_1
  - setuptools=65.6.3=py38h06a4308_0
  - sip=6.7.6=py38h8dc9893_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.40.1=h5082296_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tenacity=8.0.1=py38h06a4308_1
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py38h0a891b7_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - unicodedata2=15.0.0=py38h0a891b7_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.10=h5eee18b_1
  - yaml-cpp=0.7.0=h27087fc_2
  - zlib=1.2.13=h166bdaf_4
  - zstandard=0.19.0=py38h5945529_1
  - zstd=1.5.2=h3eb15da_6
  - heterocl=0.3
  - kaleido-core=0.2.1=h3644ca4_0
