name: odp
channels:
  - conda-forge
  - cornell-zhang
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.6.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cycler=0.11.0
  - dbus=1.13.6
  - decorator=5.1.1
  - expat=2.4.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.34.4
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.72.1
  - glib-tools=2.72.1
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - icu=69.1
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm13=13.0.1
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.4
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.3
  - libwebp-base=1.2.3
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.12
  - llvmdev=6.0.0
  - lz4-c=1.9.3
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - munkres=1.1.4
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - ncurses=6.3
  - networkx=2.8.5
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.1
  - openjpeg=2.4.0
  - openssl=3.0.5
  - ordered-set=4.1.0
  - packaging=21.3
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - qt=5.12.9
  - readline=8.1.2
  - setuptools=63.2.0
  - six=1.16.0
  - sqlite=3.39.2
  - tabulate=0.8.10
  - tk=8.6.12
  - tornado=6.2
  - unicodedata2=14.0.0
  - wheel=0.37.1
  - xmltodict=0.13.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - heterocl=0.3